### ISSUE TITLE
hashcat.bin issue generation

### ISSUE THREAD

**Issue by angelo337** [mbejda/HashCat#1]
hi there 
After I follow your guide in here: (http://www.mbejda.com/categorization-api-with-opennlp-and-express-js/), I am having and issue with the generation of the file: hashcat.bin, it does not work for me on apache-opennlp-1.6.0, with a cutoff of 5 by default, with the following command:

./opennlp DoccatTrainer -model en-doccat.bin -lang en -data hashcat.tsv -encoding UTF-8

it return this message:

`Indexing events using cutoff of 5

	Computing event counts...  done. 5245 events
	Indexing...  Dropped event food:[bow=spicy]
Dropped event food:[bow=coffeeaddict]
Dropped event food:[bow=orange]
Dropped event food:[bow=chocolate]......
`

after a long list of dropping I get:
`done.
Sorting and merging events... Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at opennlp.tools.ml.model.AbstractDataIndexer.sortAndMerge(AbstractDataIndexer.java:89)
	at opennlp.tools.ml.model.TwoPassDataIndexer.<init>(TwoPassDataIndexer.java:105)
	at opennlp.tools.ml.AbstractEventTrainer.getDataIndexer(AbstractEventTrainer.java:74)
	at opennlp.tools.ml.AbstractEventTrainer.train(AbstractEventTrainer.java:91)
	at opennlp.tools.ml.model.TrainUtil.train(TrainUtil.java:53)
	at opennlp.tools.doccat.DocumentCategorizerME.train(DocumentCategorizerME.java:204)
	at opennlp.tools.cmdline.doccat.DoccatTrainerTool.run(DoccatTrainerTool.java:76)
	at opennlp.tools.cmdline.CLI.main(CLI.java:224)`

however in apache-opennlp-1.5.3 with  parameter cutoff 1 work with no complaining with this command:

`./opennlp DoccatTrainer -model en-doccat.bin -lang en -data hashcat.tsv -encoding UTF-8 -cutoff 1`

and return:

`Indexing events using cutoff of 1

	Computing event counts...  done. 5245 events
	Indexing...  done.
Sorting and merging events... done. Reduced 5245 events to 5245.
Done indexing.
Incorporating indexed data for training...  
done.
	Number of Event Tokens: 5245
	    Number of Outcomes: 8
	  Number of Predicates: 5245
...done.
Computing model parameters ...
Performing 100 iterations.
  1:  ... loglikelihood=-10906.670886110722	0.15900857959961867
  2:  ... loglikelihood=-3297.052418670101	1.0
  3:  ... loglikelihood=-2008.7943630834177	1.0....`

and after a long list of 1.0 return:

`100:  ... loglikelihood=-52.63843463823193	1.0
Writing document categorizer model ... done (0.106s)

Wrote document categorizer model to
path: /home/user/Downloads/apache-opennlp-1.5.3/bin/en-doccat.bin`

is that the right behavior? could you please check that for me and let me know?
thanks

**Comment by mbejda** [comment]
I will look into this.

**Comment by mbejda** [comment]
It appears that `-iterations` and `-cutoff` are not argument options in OpenNLP 1.6.0. 
<img width="1429" alt="screen shot 2016-11-09 at 7 50 50 pm" src="https://cloud.githubusercontent.com/assets/5429780/20160637/77863366-a6b6-11e6-819f-2c0bf8620818.png">

I have created a params file and added the parameters into the file and ran the following command : 
`opennlp DoccatTrainer -params params.txt -model en-doccat.bin -lang en -data hashcat.tsv -encoding UTF-8` and that worked fine for me. 

**params.txt**

``` text
Algorithm=MAXENT
Iterations=150
Cutoff=1
```

The cutoff is relative to the amount of n-grams you have per line. Having a higher cutoff then n-grams will result in the error your having. 

Here is more info on cutoff and n-grams.

http://stackoverflow.com/questions/30238014/what-is-the-meaning-of-cut-off-and-iteration-for-trainings-in-opennlp

**Comment by angelo337** [comment]
thanks a lot for your answer, I will test it and let you know

angelo

**Comment by angelo337** [comment]
Hi there
thanks, I just try it and work for me that solutions, could you please tell me where should I place the file? (en-doccat.bin) should be place in the directory of the app? or in the OPENNLP directory?
thanks
